apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iris-app
  template:
    metadata:
      labels:
        app: iris-app
    spec:
      containers:
        - name: iris-app
          image: localhost/iris-app:latest
          ports:
            - containerPort: 5000
